// Generated by gencpp from file gator_basic_communications/AddTwoInts.msg
// DO NOT EDIT!


#ifndef GATOR_BASIC_COMMUNICATIONS_MESSAGE_ADDTWOINTS_H
#define GATOR_BASIC_COMMUNICATIONS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <gator_basic_communications/AddTwoIntsRequest.h>
#include <gator_basic_communications/AddTwoIntsResponse.h>


namespace gator_basic_communications
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace gator_basic_communications


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gator_basic_communications::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::gator_basic_communications::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::gator_basic_communications::AddTwoInts > {
  static const char* value()
  {
    return "gator_basic_communications/AddTwoInts";
  }

  static const char* value(const ::gator_basic_communications::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::gator_basic_communications::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::gator_basic_communications::AddTwoInts > 
template<>
struct MD5Sum< ::gator_basic_communications::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gator_basic_communications::AddTwoInts >::value();
  }
  static const char* value(const ::gator_basic_communications::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gator_basic_communications::AddTwoIntsRequest> should match 
// service_traits::DataType< ::gator_basic_communications::AddTwoInts > 
template<>
struct DataType< ::gator_basic_communications::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::gator_basic_communications::AddTwoInts >::value();
  }
  static const char* value(const ::gator_basic_communications::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gator_basic_communications::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::gator_basic_communications::AddTwoInts > 
template<>
struct MD5Sum< ::gator_basic_communications::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gator_basic_communications::AddTwoInts >::value();
  }
  static const char* value(const ::gator_basic_communications::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gator_basic_communications::AddTwoIntsResponse> should match 
// service_traits::DataType< ::gator_basic_communications::AddTwoInts > 
template<>
struct DataType< ::gator_basic_communications::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::gator_basic_communications::AddTwoInts >::value();
  }
  static const char* value(const ::gator_basic_communications::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GATOR_BASIC_COMMUNICATIONS_MESSAGE_ADDTWOINTS_H
