// Generated by gencpp from file gator_msgs/GlobalPose.msg
// DO NOT EDIT!


#ifndef GATOR_MSGS_MESSAGE_GLOBALPOSE_H
#define GATOR_MSGS_MESSAGE_GLOBALPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gator_msgs
{
template <class ContainerAllocator>
struct GlobalPose_
{
  typedef GlobalPose_<ContainerAllocator> Type;

  GlobalPose_()
    : header()
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , roll(0.0)
    , pitch(0.0)
    , heading(0.0)  {
    }
  GlobalPose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , roll(0.0)
    , pitch(0.0)
    , heading(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _heading_type;
  _heading_type heading;




  typedef boost::shared_ptr< ::gator_msgs::GlobalPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gator_msgs::GlobalPose_<ContainerAllocator> const> ConstPtr;

}; // struct GlobalPose_

typedef ::gator_msgs::GlobalPose_<std::allocator<void> > GlobalPose;

typedef boost::shared_ptr< ::gator_msgs::GlobalPose > GlobalPosePtr;
typedef boost::shared_ptr< ::gator_msgs::GlobalPose const> GlobalPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gator_msgs::GlobalPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gator_msgs::GlobalPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gator_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'gator_msgs': ['/home/reggert/Documents/GatorROS/GatorResearch/master_ws/src/gator_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'diagnostic_msgs': ['/opt/ros/indigo/share/diagnostic_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gator_msgs::GlobalPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gator_msgs::GlobalPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gator_msgs::GlobalPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gator_msgs::GlobalPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gator_msgs::GlobalPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gator_msgs::GlobalPose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gator_msgs::GlobalPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b439a83f36dde2304b17f4d0b19c3f20";
  }

  static const char* value(const ::gator_msgs::GlobalPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb439a83f36dde230ULL;
  static const uint64_t static_value2 = 0x4b17f4d0b19c3f20ULL;
};

template<class ContainerAllocator>
struct DataType< ::gator_msgs::GlobalPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gator_msgs/GlobalPose";
  }

  static const char* value(const ::gator_msgs::GlobalPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gator_msgs::GlobalPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header  header\n\
float64 latitude\n\
float64 longitude\n\
float64 altitude\n\
float64 roll\n\
float64 pitch\n\
float64 heading\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::gator_msgs::GlobalPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gator_msgs::GlobalPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GlobalPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gator_msgs::GlobalPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gator_msgs::GlobalPose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GATOR_MSGS_MESSAGE_GLOBALPOSE_H
