// Generated by gencpp from file beginner_tutorials/lvarray.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_LVARRAY_H
#define BEGINNER_TUTORIALS_MESSAGE_LVARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <diagnostic_msgs/KeyValue.h>

namespace beginner_tutorials
{
template <class ContainerAllocator>
struct lvarray_
{
  typedef lvarray_<ContainerAllocator> Type;

  lvarray_()
    : testarray()  {
    }
  lvarray_(const ContainerAllocator& _alloc)
    : testarray(_alloc)  {
    }



   typedef std::vector< ::diagnostic_msgs::KeyValue_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::diagnostic_msgs::KeyValue_<ContainerAllocator> >::other >  _testarray_type;
  _testarray_type testarray;




  typedef boost::shared_ptr< ::beginner_tutorials::lvarray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::lvarray_<ContainerAllocator> const> ConstPtr;

}; // struct lvarray_

typedef ::beginner_tutorials::lvarray_<std::allocator<void> > lvarray;

typedef boost::shared_ptr< ::beginner_tutorials::lvarray > lvarrayPtr;
typedef boost::shared_ptr< ::beginner_tutorials::lvarray const> lvarrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::lvarray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::lvarray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/reggert/Documents/GatorROS/GatorResearch/master_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'diagnostic_msgs': ['/opt/ros/indigo/share/diagnostic_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::lvarray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::lvarray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::lvarray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::lvarray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::lvarray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::lvarray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::lvarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51149c98320939ae25f418c95ad7617b";
  }

  static const char* value(const ::beginner_tutorials::lvarray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51149c98320939aeULL;
  static const uint64_t static_value2 = 0x25f418c95ad7617bULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::lvarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/lvarray";
  }

  static const char* value(const ::beginner_tutorials::lvarray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::lvarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diagnostic_msgs/KeyValue[] testarray\n\
================================================================================\n\
MSG: diagnostic_msgs/KeyValue\n\
string key # what to label this value when viewing\n\
string value # a value to track over time\n\
";
  }

  static const char* value(const ::beginner_tutorials::lvarray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::lvarray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.testarray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct lvarray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::lvarray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::lvarray_<ContainerAllocator>& v)
  {
    s << indent << "testarray[]" << std::endl;
    for (size_t i = 0; i < v.testarray.size(); ++i)
    {
      s << indent << "  testarray[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::diagnostic_msgs::KeyValue_<ContainerAllocator> >::stream(s, indent + "    ", v.testarray[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_LVARRAY_H
